version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: medcloud-mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: medcloud-desafio
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
